e-arbiter:
  service-name: Tournament Results Module

spring:
  application:
    name: tournament-results-module
server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}