e-arbiter:
  swagger:
    title: test
    description: test
    contact-name: test
    contact-address: test
    contact-url: test
    path: rest-api
  clientUrl: test
  proxyUrl: test

spring:
  profiles: test
  datasource:
    name: test
    platform: h2
    url: jdbc:h2:mem:e-arbiter-tour-res-test;DATABASE_TO_UPPER=true;IGNORECASE=true;
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-test.xml

security:
  basic:
    enabled: false

eureka:
  client:
    enabled: false