e-arbiter:
  service-name: Tournament Results Module

spring:
  application:
    name: tournament-results-module

  profiles:
    active: dev

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none