language: java
jdk: oraclejdk8
dist: trusty
sudo: required

branches:
  only:
  - master

addons:
apt:
  sources:
   - google-chrome
  packages:
   - google-chrome-stable

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - nvm install 6.9.4
 - nvm use 6.9.4

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
 - npm install -g @angular/cli@1.0.0
 - npm install -g angular-cli-ghpages
 - cd e-arbiter-web
 - npm install
 - cd ..

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.nvm"
  - "e-arbiter-web/node_modules"

script:
 - echo Hello Travis for e-Arbiter
 - ./gradlew build
 - cd e-arbiter-web
 - ng build --env=prod --base-href "https://arturczopek.github.io/e-arbiter/" -aot --stats-json
# TODO uncomment, you know when..:)
# - ng test --watch=false

after_success:
 - angular-cli-ghpages --no-silent --repo=https://GH_TOKEN@github.com/arturczopek/e-arbiter.git

notifications:
  email: false
  slack:
    rooms:
      secure: hyV8HTWLz+2j6OtPiU56yXBmE9R8cwBjwFVTtVmSTLiXHav+wxNifxvg5xbMMvc8m6RQYhIjt/iJkOTyYIKzwMkSmmpDJj2p+xfvCJ2nWHJXg83xt7YplN3jc9a8qcrgI9nARjSq17AUfGFXmYKsuNW9E+BfS2oD3YAhxOTJaGrJyUZfOYh7m9yOJm5t26sCiY2CXR5BsIqcLAnllW0UyzKnsG8sxGooeZsoerwcwazqP2g/KMAe3U9V4nZhbFdltXfWinqjT+2ii3YzXOG1ADcf6miNQvVQYEUmf1DiCnMwodsj7qIDXUkzdzKgdLZt9F5OXSt6v+TaxdqWh1hB+Ax/F1asSlCyI/v42wZJxAMmshycmZLshpvKcuIv2G7Xp6Ln0U+3bJ3/UutZFqZ7mGbA007GC4jZQE8Z/kpIeDU1RdzVg35A2eZr0fyr82maIihzsVS32v4Bo7DcllSBolF8WPnKWWmD4GBPOGGIC9Gieqhz2nqwNcOzEkxvcLg4RUIr6YOIsVKUT1CX5IAMhGOjS6qf8DI5wDSdf1rniWdAPjm2asmH0SlXRoOJltOd7AfPgXohc392zfYb/YoSxxxISzQJkxW3tkl4LyXTFZAq1uGXXD5/PSKpifeTqEMxiQ43EuqhQlAhcdUGliuyMWUffWNE9N3P3hgJ8HuiCzU=
