language: java
jdk: oraclejdk8
services: mongodb
dist: trusty
sudo: required
install: true

branches:
  only:
  - master

apt:
  sources:
   - google-chrome
  packages:
   - google-chrome-stable

before_install:
 - chmod +x ./scripts/**
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - nvm install 6.9.4
 - nvm use 6.9.4
 - sudo apt-get install lynx lynx-cur

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
 - npm install -g @angular/cli@1.0.0
 - npm install -g angular-cli-ghpages
 - cd e-arbiter-web
 - npm install
 - cd $TRAVIS_BUILD_DIR

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.sonar/cache"
  - ".gradle"
  - "$HOME/.nvm"
  - "e-arbiter-web/node_modules"

script:
 - ./scripts/build.sh

after_success:
 - ./scripts/publish.sh

 # This is only for "debug" purposes on Travis. We cannot get files from there but you can't print them, for example report from test
 # You can print proper file by setting $TEST_FILE_PATH env variable in Travis which already exists
 # REMEMBER THAT IT SHOULD BE VISIBLE IN LOGS! We can reuse it later and easily change
after_failure:
 - if [ -f $TEST_FILE_PATH ]; then lynx -dump $TEST_FILE_PATH; fi

notifications:
  email: false
  slack:
    rooms:
      secure: hyV8HTWLz+2j6OtPiU56yXBmE9R8cwBjwFVTtVmSTLiXHav+wxNifxvg5xbMMvc8m6RQYhIjt/iJkOTyYIKzwMkSmmpDJj2p+xfvCJ2nWHJXg83xt7YplN3jc9a8qcrgI9nARjSq17AUfGFXmYKsuNW9E+BfS2oD3YAhxOTJaGrJyUZfOYh7m9yOJm5t26sCiY2CXR5BsIqcLAnllW0UyzKnsG8sxGooeZsoerwcwazqP2g/KMAe3U9V4nZhbFdltXfWinqjT+2ii3YzXOG1ADcf6miNQvVQYEUmf1DiCnMwodsj7qIDXUkzdzKgdLZt9F5OXSt6v+TaxdqWh1hB+Ax/F1asSlCyI/v42wZJxAMmshycmZLshpvKcuIv2G7Xp6Ln0U+3bJ3/UutZFqZ7mGbA007GC4jZQE8Z/kpIeDU1RdzVg35A2eZr0fyr82maIihzsVS32v4Bo7DcllSBolF8WPnKWWmD4GBPOGGIC9Gieqhz2nqwNcOzEkxvcLg4RUIr6YOIsVKUT1CX5IAMhGOjS6qf8DI5wDSdf1rniWdAPjm2asmH0SlXRoOJltOd7AfPgXohc392zfYb/YoSxxxISzQJkxW3tkl4LyXTFZAq1uGXXD5/PSKpifeTqEMxiQ43EuqhQlAhcdUGliuyMWUffWNE9N3P3hgJ8HuiCzU=
