webpackJsonp([0,6],{

/***/ 218:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(4);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_dashboard_dashboard_module__ = __webpack_require__(110);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__(17);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_forms__ = __webpack_require__(107);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_http__ = __webpack_require__(66);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__angular_router__ = __webpack_require__(7);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__app_dashboard_dashboard_routing__ = __webpack_require__(111);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__dashboard_component_ngfactory__ = __webpack_require__(108);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_8__user_data_component_ngfactory__ = __webpack_require__(109);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_9__app_dashboard_dashboard_component__ = __webpack_require__(35);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_10__app_dashboard_user_data_component__ = __webpack_require__(36);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_11__app_shared_guard_logged_in_user_guard__ = __webpack_require__(67);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "DashboardModuleNgFactory", function() { return DashboardModuleNgFactory; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();












var DashboardModuleInjector = (function (_super) {
    __extends(DashboardModuleInjector, _super);
    function DashboardModuleInjector(parent) {
        return _super.call(this, parent, [
            __WEBPACK_IMPORTED_MODULE_7__dashboard_component_ngfactory__["a" /* DashboardComponentNgFactory */],
            __WEBPACK_IMPORTED_MODULE_8__user_data_component_ngfactory__["a" /* UserDataComponentNgFactory */]
        ], []) || this;
    }
    Object.defineProperty(DashboardModuleInjector.prototype, "_NgLocalization_7", {
        get: function () {
            if ((this.__NgLocalization_7 == null)) {
                (this.__NgLocalization_7 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["a" /* NgLocaleLocalization */](this.parent.get(__WEBPACK_IMPORTED_MODULE_0__angular_core__["c" /* LOCALE_ID */])));
            }
            return this.__NgLocalization_7;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_\u0275i_8", {
        get: function () {
            if ((this.__ɵi_8 == null)) {
                (this.__ɵi_8 = new __WEBPACK_IMPORTED_MODULE_3__angular_forms__["a" /* ɵi */]());
            }
            return this.__ɵi_8;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_BrowserXhr_9", {
        get: function () {
            if ((this.__BrowserXhr_9 == null)) {
                (this.__BrowserXhr_9 = new __WEBPACK_IMPORTED_MODULE_4__angular_http__["a" /* BrowserXhr */]());
            }
            return this.__BrowserXhr_9;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_ResponseOptions_10", {
        get: function () {
            if ((this.__ResponseOptions_10 == null)) {
                (this.__ResponseOptions_10 = new __WEBPACK_IMPORTED_MODULE_4__angular_http__["b" /* BaseResponseOptions */]());
            }
            return this.__ResponseOptions_10;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_XSRFStrategy_11", {
        get: function () {
            if ((this.__XSRFStrategy_11 == null)) {
                (this.__XSRFStrategy_11 = __WEBPACK_IMPORTED_MODULE_4__angular_http__["c" /* ɵb */]());
            }
            return this.__XSRFStrategy_11;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_XHRBackend_12", {
        get: function () {
            if ((this.__XHRBackend_12 == null)) {
                (this.__XHRBackend_12 = new __WEBPACK_IMPORTED_MODULE_4__angular_http__["d" /* XHRBackend */](this._BrowserXhr_9, this._ResponseOptions_10, this._XSRFStrategy_11));
            }
            return this.__XHRBackend_12;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_RequestOptions_13", {
        get: function () {
            if ((this.__RequestOptions_13 == null)) {
                (this.__RequestOptions_13 = new __WEBPACK_IMPORTED_MODULE_4__angular_http__["e" /* BaseRequestOptions */]());
            }
            return this.__RequestOptions_13;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(DashboardModuleInjector.prototype, "_Http_14", {
        get: function () {
            if ((this.__Http_14 == null)) {
                (this.__Http_14 = __WEBPACK_IMPORTED_MODULE_4__angular_http__["f" /* ɵc */](this._XHRBackend_12, this._RequestOptions_13));
            }
            return this.__Http_14;
        },
        enumerable: true,
        configurable: true
    });
    DashboardModuleInjector.prototype.createInternal = function () {
        this._CommonModule_0 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */]();
        this._ɵba_1 = new __WEBPACK_IMPORTED_MODULE_3__angular_forms__["b" /* ɵba */]();
        this._FormsModule_2 = new __WEBPACK_IMPORTED_MODULE_3__angular_forms__["c" /* FormsModule */]();
        this._HttpModule_3 = new __WEBPACK_IMPORTED_MODULE_4__angular_http__["g" /* HttpModule */]();
        this._RouterModule_4 = new __WEBPACK_IMPORTED_MODULE_5__angular_router__["q" /* RouterModule */](this.parent.get(__WEBPACK_IMPORTED_MODULE_5__angular_router__["r" /* ɵa */], null), this.parent.get(__WEBPACK_IMPORTED_MODULE_5__angular_router__["j" /* Router */], null));
        this._DashboardRouting_5 = new __WEBPACK_IMPORTED_MODULE_6__app_dashboard_dashboard_routing__["a" /* DashboardRouting */]();
        this._DashboardModule_6 = new __WEBPACK_IMPORTED_MODULE_1__app_dashboard_dashboard_module__["a" /* DashboardModule */]();
        this._ROUTES_15 = [[{
                    path: '',
                    component: __WEBPACK_IMPORTED_MODULE_9__app_dashboard_dashboard_component__["a" /* DashboardComponent */],
                    children: [
                        {
                            path: '',
                            pathMatch: 'full',
                            redirectTo: 'data'
                        },
                        {
                            path: 'data',
                            component: __WEBPACK_IMPORTED_MODULE_10__app_dashboard_user_data_component__["a" /* UserDataComponent */],
                            canActivate: [__WEBPACK_IMPORTED_MODULE_11__app_shared_guard_logged_in_user_guard__["a" /* LoggedInUserGuard */]]
                        }
                    ]
                }
            ]];
        return this._DashboardModule_6;
    };
    DashboardModuleInjector.prototype.getInternal = function (token, notFoundResult) {
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */])) {
            return this._CommonModule_0;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_forms__["b" /* ɵba */])) {
            return this._ɵba_1;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_forms__["c" /* FormsModule */])) {
            return this._FormsModule_2;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["g" /* HttpModule */])) {
            return this._HttpModule_3;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_5__angular_router__["q" /* RouterModule */])) {
            return this._RouterModule_4;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_6__app_dashboard_dashboard_routing__["a" /* DashboardRouting */])) {
            return this._DashboardRouting_5;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_1__app_dashboard_dashboard_module__["a" /* DashboardModule */])) {
            return this._DashboardModule_6;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["g" /* NgLocalization */])) {
            return this._NgLocalization_7;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_forms__["a" /* ɵi */])) {
            return this._ɵi_8;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["a" /* BrowserXhr */])) {
            return this._BrowserXhr_9;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["h" /* ResponseOptions */])) {
            return this._ResponseOptions_10;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["i" /* XSRFStrategy */])) {
            return this._XSRFStrategy_11;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["d" /* XHRBackend */])) {
            return this._XHRBackend_12;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["j" /* RequestOptions */])) {
            return this._RequestOptions_13;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__angular_http__["k" /* Http */])) {
            return this._Http_14;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_5__angular_router__["u" /* ROUTES */])) {
            return this._ROUTES_15;
        }
        return notFoundResult;
    };
    DashboardModuleInjector.prototype.destroyInternal = function () {
    };
    return DashboardModuleInjector;
}(__WEBPACK_IMPORTED_MODULE_0__angular_core__["B" /* ɵNgModuleInjector */]));
var DashboardModuleNgFactory = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["C" /* NgModuleFactory */](DashboardModuleInjector, __WEBPACK_IMPORTED_MODULE_1__app_dashboard_dashboard_module__["a" /* DashboardModule */]);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdHJhdmlzL2J1aWxkL0FydHVyQ3pvcGVrL2UtYXJiaXRlci9lLWFyYml0ZXItd2ViL3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2hib2FyZC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS90cmF2aXMvYnVpbGQvQXJ0dXJDem9wZWsvZS1hcmJpdGVyL2UtYXJiaXRlci13ZWIvc3JjL2FwcC9kYXNoYm9hcmQvZGFzaGJvYXJkLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
//# sourceMappingURL=dashboard.module.ngfactory.js.map

/***/ })

});
//# sourceMappingURL=0.chunk.js.map