version: '2.1'

# You need to create e-arbiter network. If you have one, it's ok. If not, check guide how to do it
# The simplest way to run it: docker-compose up
# To stop, type: docker-compose down
# For additional flags (like detach etc), use --help

services:
  mongo:
    image: earbiterinfo/e-arbiter-mongo
    ports:
    - 192.168.0.1:27017:27017
#    - $E_ARB_DEV_TOUR_MONGO_HOST:$E_ARB_DEV_TOUR_MONGO_PORT:27017      # In case of using another port
#    environment:
#      MONGODB_USER: $E_ARB_DEV_TOUR_MONGO_USERNAME           # in case of using different db data
#      MONGODB_PASS: $E_ARB_DEV_TOUR_MONGO_PASSWORD           # in case of using different db data
#      E_ARB_DEV_TOUR_MONGO_HOST: $E_ARB_DEV_TOUR_MONGO_HOST  # in case of using different db data

  config:
    image: earbiterinfo/e-arbiter-config
    ports:
    - 8096:8096
#    - $E_ARB_CFG_PORT:$E_ARB_CFG_PORT    # In case of using another port
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      E_ARB_USR_NAME: e-Arbiter
      E_ARB_USR_PASS: $E_ARB_USR_PASS
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT      # In case of using another port

  eureka:
    image: earbiterinfo/e-arbiter-eureka
    ports:
    - 8761:8761
#    - $E_ARB_EUR_PORT:$E_ARB_EUR_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#    environment:
#      E_ARB_EUR_PORT: $E_ARB_EUR_PORT     # In case of using another port
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT     # In case of using another port

  api-gateway:
    image: earbiterinfo/e-arbiter-api-gateway
    ports:
    - 8080:8080
#    - $E_ARB_API_PORT:$E_ARB_API_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#    environment:
#      E_ARB_AUTH_PORT: $E_ARB_AUTH_PORT         # In case of using another port
#      E_ARB_EXEC_PORT: $E_ARB_EXEC_PORT         # In case of using another port
#      E_ARB_TOUR_PORT: $E_ARB_TOUR_PORT         # In case of using another port
#      E_ARB_TRES_PORT: $E_ARB_TRES_PORT         # In case of using another port
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT           # In case of using another port

  auth:
    image: earbiterinfo/e-arbiter-auth
    ports:
    - 8090:8090
#    - $E_ARB_AUTH_PORT:$E_ARB_AUTH_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      E_ARB_DEV_GH_CLIENT_ID: $E_ARB_DOCK_DEV_GH_CLIENT_ID
      E_ARB_DEV_GH_CLIENT_SECRET: $E_ARB_DOCK_DEV_GH_CLIENT_SECRET
#      E_ARB_AUTH_PORT: $E_ARB_AUTH_PORT      # In case of using another port
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT      # In case of using another port

  executor:
    image: earbiterinfo/e-arbiter-executor
    ports:
    - 8091:8091
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $E_ARB_DEV_EXEC_BINDING:$E_ARB_DEV_EXEC_BINDING
#    - $E_ARB_EXEC_PORT:$E_ARB_EXEC_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      E_ARB_DEV_EXEC_BINDING: $E_ARB_DEV_EXEC_BINDING
#      E_ARB_EXEC_PORT:$E_ARB_EXEC_PORT      # In case of using another port

  tournament:
    image: earbiterinfo/e-arbiter-tournament
    ports:
    - 8092:8092
#    - $E_ARB_TOUR_PORT:$E_ARB_TOUR_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      E_ARB_TOUR_MAIL_PASSWORD: $E_ARB_USR_PASS
#      E_ARB_AUTH_PORT: $E_ARB_AUTH_PORT                               # In case of using another port
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT                                 # In case of using another port
#      E_ARB_TOUR_PORT: $E_ARB_TOUR_PORT                               # In case of using another port
#      E_ARB_DEV_TOUR_MONGO_USERNAME: $E_ARB_DEV_TOUR_MONGO_USERNAME   # in case of using different db data
#      E_ARB_DEV_TOUR_MONGO_USERNAME: $E_ARB_DEV_TOUR_MONGO_PASSWORD   # in case of using different db data

  tournament-results:
    image: earbiterinfo/e-arbiter-tournament-results
    ports:
    - 8093:8093
#    - $E_ARB_TRES_PORT:$E_ARB_TRES_PORT      # In case of using another port
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#    environment:
#      E_ARB_AUTH_PORT: $E_ARB_AUTH_PORT      # In case of using another port
#      E_ARB_CFG_PORT: $E_ARB_CFG_PORT      # In case of using another port
#      E_ARB_TRES_PORT: $E_ARB_TRES_PORT      # In case of using another port
#

  web:
    image: earbiterinfo/e-arbiter-web
    ports:
    - 4200:80
#    - $E_ARB_CLIENT_PORT:80      # In case of using another port
    restart: always
#    environment:
#      E_ARB_CLIENT_PORT: $E_ARB_CLIENT_PORT      # In case of using another port

networks:
  default:
    external:
      name: e-arbiter
