e-arbiter:
  service-name: API Gateway

spring:
  application:
    name: api-gateway
server:
  port: 8080

zuul:
  routes:
    # TODO move ports and adresses to env variables
    authentication-module:
      path: /auth/**
      url: http://localhost:8090

    # TODO move ports and adresses to env variables
    executor-module:
      path: /exec/**
      url: http://localhost:8091

    # TODO move ports and adresses to env variables
    tournament-module:
      path: /tournament/**
      url: http://localhost:8092

    # TODO move ports and adresses to env variables
    tournament-results-module:
      path: /results/**
      url: http://localhost:8093

    # TODO move ports and adresses to env variables
    solution-repository-module:
      path: /solution/**
      url: http://localhost:8094