e-arbiter:
  swagger:
    title: e-Arbiter - Solution Repository Module
    description: API for Solution Repository Module
    contact-name: cyganki
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api

spring:
  profiles: dev

server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}