e-arbiter:
  service-name: Eureka Server

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# workaround for actuator endpoints for now
management.security.enabled: false