e-arbiter:
  service-name: Eureka Server

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# workaround for actuator endpoints for now
management.security.enabled: false