e-arbiter:
  swagger:
    title: test
    description: test
    contact-name: test
    contact-address: test
    contact-url: test
    path: rest-api
  clientUrl: test
  proxyUrl: test

spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

security:
  basic:
    enabled: false

eureka:
  client:
    enabled: false