e-arbiter:
  service-name: Tournament Module

spring:
  application:
    name: tournament-module
  profiles:
    active: dev
  data:
      mongodb:
        host: localhost
        port: 27017
        database: e-arbiter