e-arbiter:
  service-name: Authentication Module

spring:
  application:
    name: authentication-module
  profiles:
    active: dev

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
#      clientId: ${E_ARB_GH_CLIENT_ID_DEV}
    clientId: f75c26a0d24ebad596d9
#      clientSecret: ${E_ARB_GH_CLIENT_SECRET_DEV}
    clientSecret: 225d8358508e38db5128cd1b63fc59b5adb6e8fb
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: repo, user
  resource:
    userInfoUri: https://api.github.com/user