e-arbiter:
  swagger:
    title: e-Arbiter - Authentication Module
    description: API for Authentication Module
    contact-name: cyganki
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api
  clientUrl: http://localhost:4200
  proxyUrl: http://localhost:8080

spring:
  profiles: dev

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      clientId: ${E_ARB_GH_CLIENT_ID_DEV}
      clientSecret: ${E_ARB_GH_CLIENT_SECRET_DEV}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope: repo, user
    resource:
      userInfoUri: https://api.github.com/user