e-arbiter:
  swagger:
    title: e-Arbiter - Authentication Module
    description: API for Authentication Module
    contact-name: cyganki
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api
  clientUrl: http://localhost:4200
  proxyUrl: http://localhost:8080

spring:
  profiles: test

server:
  port: 8090

security:
  basic:
    enabled: false

eureka:
  client:
    enabled: false