e-arbiter:
  service-name: ${E_ARB_CFG_NAME}

server:
  port: ${E_ARB_CFG_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: INFO
    pl:
      cyganki: DEBUG