e-arbiter:
  service-name: Executor Module

spring:
  application:
    name: executor-module
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}